config/routes.rb
Rails.application.routes.draw do
  root "students#index"

  resources :students do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

  validates :surname, presence: true
  validates :school, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
    @prize_schools = Student.select("DISTINCT school").where("place > 0")
    @most_successful_school = Student.select("school, count(place) as total_prize").where("place > 0").
      group(:school).order("total_prize DESC").limit(5)
    @winners = Student.select("surname, school, grade").where("place = 1")

    # Order.select("date(created_at) as ordered_date, sum(price) as total_price").group("date(created_at)").having("sum(price) > ?", 100)
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to @student
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to root_path
  end

  private
  def student_params
    params.require(:student).permit(:surname, :school, :grade, :place, :total_prize)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Olympiad</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>
      <div>
        <%= form.label :surname %><br>
        <%= form.text_field :surname %>
        <% student.errors.full_messages_for(:surname).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div>
        <%= form.label :school %><br>
        <%= form.text_field :school %><br>
        <% student.errors.full_messages_for(:school).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div>
        <%= form.label :grade %><br>
        <%= form.select :grade, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], selected: 1 %><br>
      </div>

      <div>
        <%= form.label :place %><br>
        <%= form.select :place, [0, 1, 2, 3], selected: 0%><br>
      </div>

      <div>
        <button class="btn"><%= form.submit %></button>
      </div>
<% end %>

app/views/students/edit.html.erb
<body>
  <div class="container">
    <h1>Edit Student</h1>

    <%= render "form", student: @student %>
  </div>
</body>

app/views/students/index.html.erb
<%= stylesheet_link_tag 'students.css' %>

<body>
    <div class="container">
      <h1><%= link_to "New student", new_student_path %></h1>


      <h1>Students</h1>

    <table>
      <tr>
        <th>Surname</th>
        <th>School</th>
        <th>Grade</th>
        <th>Place</th>

      </tr>
      <% @students.each do |student| %>
        <tr>
          <th><%= link_to student.surname, student%></th>
          <th><%= student.school%></th>
          <th><%= student.grade%></th>
          <th><%= student.place%></th>
        </tr>
      <% end %>
    </table>

    <h1>Schools with prize places</h1>
    <table>
      <% @prize_schools.each do |student| %>
        <tr>
          <th><%= student.school %></th>
        </tr>
      <% end %>
    </table>

    <h1>Most successful schools</h1>
    <table>
      <tr>
        <th>School</th>
        <th>Total prizes</th>
      </tr>
      <% @most_successful_school.each do |student| %>
        <tr>
          <th><%= student.school %></th>
          <th><%= student.total_prize %></th>
        </tr>
      <% end %>
    </table>

    <h1>First place winners</h1>
    <table>
      <tr>
        <th>Surname</th>
        <th>School</th>
        <th>Grade</th>
      </tr>
      <% @winners.each do |student| %>
        <tr>
          <th><%= student.surname %></th>
          <th><%= student.school %></th>
          <th><%= student.grade %></th>
        </tr>
      <% end %>
    </table>

    </div>
</body>

app/views/students/new.html.erb
<body>
  <div class="container">
    <h1>New Student</h1>

    <%= render "form", student: @student %>
  </div>
</body>

app/views/students/show.html.erb
<body>
  <div class="container">
    <h1>Surname: <%= @student.surname %></h1>


    <p>School:  <%= @student.school %></p>
    <p>Grade: <%= @student.grade %></p>
    <p>Place: <%= @student.place %></p>


    <h2><%= link_to "Edit", edit_student_path(@student) %></h2>
      <h2><%= link_to "Destroy", student_path(@student),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %></h2>
      <h2><%= link_to "Home", "/"%></h2>
  </div>
</body>